# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    # Install uv and dependencies
    - pip install uv
    - uv sync
    # Build Sphinx documentation
    - uv run sphinx-build -b html docs/source $READTHEDOCS_OUTPUT/html

